version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: churn-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: churn-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  mongodb:
    image: mongo:7.0
    container_name: churn-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastapi:
    build: .
    container_name: churn-fastapi
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      MONGO_URI: mongodb://mongodb:27017
      MONGO_DB: churn_platform
      MONGO_COLLECTION: churn_predictions
      MLFLOW_TRACKING_URI: sqlite:///mlflow.db
      MLFLOW_ALLOW_FILE_STORE: "true"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./reports:/app/reports
      - ./mlruns:/app/mlruns
    depends_on:
      - mongodb

  streamlit:
    build: .
    container_name: churn-streamlit
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      API_PREDICT_URL: http://fastapi:8000/predict
      MLFLOW_TRACKING_URI: sqlite:///mlflow.db
      MLFLOW_ALLOW_FILE_STORE: "true"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./reports:/app/reports
      - ./mlruns:/app/mlruns
    depends_on:
      - fastapi

volumes:
  mongo_data:
